---
kind: pipeline
name: linting

platform:
  os: linux
  arch: amd64

steps:
- name: later
  image: xoxys/ansible-later:latest
  commands:
  - ansible-later

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: documentation

platform:
  os: linux
  arch: amd64

steps:
- name: generate
  image: xoxys/ansible-doctor:latest
  environment:
    ANSIBLE_DOCTOR_EXCLUDE_FILES: molecule/
    ANSIBLE_DOCTOR_FORCE_OVERWRITE: true
    ANSIBLE_DOCTOR_LOG_LEVEL: INFO
    ANSIBLE_DOCTOR_OUTPUT_DIR: _docs/
    ANSIBLE_DOCTOR_TEMPLATE: hugo

- name: publish
  image: plugins/gh-pages:latest
  settings:
    pages_directory: _docs/
    password:
      from_secret: github_token
    target_branch: docs
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/master

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- testing-ubuntu1804
- testing-centos7

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: docs
  image: plugins/downstream
  settings:
    fork: true
    repositories:
    - owncloud-ansible/owncloud-ansible.github.io@source
    server: https://drone.owncloud.com
    token:
      from_secret: drone_token

- name: notify
  image: plugins/slack:1
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- linting
- testing-ubuntu1804
- testing-centos7
- documentation

---
kind: signature
hmac: 7d57d162d3fb56cd36e60402971578f8b87bd22d7fb88d7ef1a7b3f716bd603a

...
