---
kind: pipeline
name: linting

platform:
  os: linux
  arch: amd64

steps:
- name: later
  image: xoxys/ansible-later:latest
  commands:
  - ansible-later

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: testing-ubuntu1804

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
- name: molecule
  image: xoxys/molecule:hcloud-linux-amd64
  commands:
  - /bin/bash /docker-entrypoint.sh
  - molecule test -s ubuntu1804
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: testing-centos7

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
- name: molecule
  image: xoxys/molecule:hcloud-linux-amd64
  commands:
  - /bin/bash /docker-entrypoint.sh
  - molecule test -s centos7
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: documentation

platform:
  os: linux
  arch: amd64

steps:
- name: generate
  image: xoxys/ansible-doctor:latest
  environment:
    ANSIBLE_DOCTOR_EXCLUDE_FILES: molecule/
    ANSIBLE_DOCTOR_FORCE_OVERWRITE: true
    ANSIBLE_DOCTOR_LOG_LEVEL: INFO
    ANSIBLE_DOCTOR_THEME: hugo
    ANSIBLE_DOCTOR_OUTPUT_DIR: _docs/

- name: publish
  image: plugins/gh-pages:latest
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: _docs/
    target_branch: docs
  when:
    ref:
    - refs/heads/master

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- testing-ubuntu1804
- testing-centos7

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack:1
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- linting
- testing-ubuntu1804
- testing-centos7
- documentation

---
kind: signature
hmac: 22709de416baf025f7a7ef444c61e3073b8966780c356bd79618fa6d40138c7c

...
